//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.nng.bs15;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.GridView;
import com.nng.bs15.R.layout;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class RegisterDatasFragment_
    extends com.nng.bs15.RegisterDatasFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_register_datas, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static RegisterDatasFragment_.FragmentBuilder_ builder() {
        return new RegisterDatasFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        save = ((Button) hasViews.findViewById(com.nng.bs15.R.id.reg_save));
        reg_text = ((EditText) hasViews.findViewById(com.nng.bs15.R.id.reg_text));
        reg_keyboard = ((GridView) hasViews.findViewById(com.nng.bs15.R.id.reg_keyboard));
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<RegisterDatasFragment_.FragmentBuilder_, com.nng.bs15.RegisterDatasFragment>
    {


        @Override
        public com.nng.bs15.RegisterDatasFragment build() {
            RegisterDatasFragment_ fragment_ = new RegisterDatasFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
