//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.nng.bs15;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.Button;
import com.nng.bs15.R.layout;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class SelectActionFragment_
    extends com.nng.bs15.SelectActionFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_select_action, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        app = BS15Application_.getInstance();
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static SelectActionFragment_.FragmentBuilder_ builder() {
        return new SelectActionFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        sel_add_new_learning_data = ((Button) hasViews.findViewById(com.nng.bs15.R.id.sel_add_new_learning_data));
        sel_add_new_test_data = ((Button) hasViews.findViewById(com.nng.bs15.R.id.sel_add_new_test_data));
        if (sel_add_new_learning_data!= null) {
            sel_add_new_learning_data.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    SelectActionFragment_.this.onClick(view);
                }

            }
            );
        }
        if (sel_add_new_test_data!= null) {
            sel_add_new_test_data.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    SelectActionFragment_.this.onClick(view);
                }

            }
            );
        }
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<SelectActionFragment_.FragmentBuilder_, com.nng.bs15.SelectActionFragment>
    {


        @Override
        public com.nng.bs15.SelectActionFragment build() {
            SelectActionFragment_ fragment_ = new SelectActionFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
